"""Writes hostkey.h with a fresh random ed25519 seed. Run once; keep the file so clients see a stable host key."""

import os
import sys


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "hostkey.h"
    seed = os.urandom(32)
    body = ", ".join("0x%02x" % b for b in seed)
    with open(out, "w", newline="\n") as f:
        f.write("/* Generated by genkey.py. ed25519 private key seed for the SSH host key. Keep it private, do not commit it. */\n")
        f.write("#ifndef SSH_HOSTKEY_H_\n#define SSH_HOSTKEY_H_\n\n")
        f.write("static const unsigned char HOST_KEY_SEED[32] = { %s };\n\n" % body)
        f.write("#endif\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
